// Fallback for using MaterialIcons on Android and web.

import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { SymbolWeight, SymbolViewProps } from 'expo-symbols';
import { ComponentProps } from 'react';
import { OpaqueColorValue, type StyleProp, type TextStyle } from 'react-native';

type IconSymbolName =
  | 'house.fill'
  | 'paperplane.fill'
  | 'chevron.left.forwardslash.chevron.right'
  | 'chevron.right'
  | 'chevron.left'
  | 'chevron.up'
  | 'chevron.down'
  | 'ellipsis'
  | 'ellipsis.circle'
  | 'ellipsis.circle.fill'
  | 'gear'
  | 'gear.fill'
  | 'bell'
  | 'bell.fill'
  | 'bell.slash'
  | 'bell.slash.fill'
  | 'magnifyingglass'
  | 'magnifyingglass.circle'
  | 'magnifyingglass.circle.fill'
  | 'plus'
  | 'plus.circle'
  | 'plus.circle.fill'
  | 'minus'
  | 'minus.circle'
  | 'minus.circle.fill'
  | 'arrow.up'
  | 'arrow.down'
  | 'arrow.left'
  | 'arrow.right'
  | 'arrow.up.circle'
  | 'arrow.down.circle'
  | 'arrow.left.circle'
  | 'arrow.right.circle'
  | 'arrow.up.circle.fill'
  | 'arrow.down.circle.fill'
  | 'arrow.left.circle.fill'
  | 'arrow.right.circle.fill'
  | 'star'
  | 'star.fill'
  | 'star.circle'
  | 'star.circle.fill'
  | 'heart'
  | 'heart.fill'
  | 'heart.circle'
  | 'heart.circle.fill'
  | 'trash'
  | 'trash.fill'
  | 'trash.circle'
  | 'trash.circle.fill'
  | 'pencil'
  | 'pencil.circle'
  | 'pencil.circle.fill'
  | 'checkmark'
  | 'checkmark.circle'
  | 'checkmark.circle.fill'
  | 'xmark'
  | 'xmark.circle'
  | 'xmark.circle.fill'
  | 'eye'
  | 'eye.fill'
  | 'eye.slash'
  | 'eye.slash.fill'
  | 'person'
  | 'person.fill'
  | 'person.circle'
  | 'person.circle.fill'
  | 'calendar'
  | 'calendar.circle'
  | 'calendar.circle.fill'
  | 'clock'
  | 'clock.fill'
  | 'clock.circle'
  | 'clock.circle.fill'
  | 'camera'
  | 'camera.fill'
  | 'camera.circle'
  | 'camera.circle.fill'
  | 'photo'
  | 'photo.fill'
  | 'photo.circle'
  | 'photo.circle.fill'
  | 'folder'
  | 'folder.fill'
  | 'folder.circle'
  | 'folder.circle.fill'
  | 'doc'
  | 'doc.fill'
  | 'doc.circle'
  | 'doc.circle.fill'
  | 'lock'
  | 'lock.fill'
  | 'lock.open'
  | 'lock.open.fill'
  | 'bookmark'
  | 'bookmark.fill'
  | 'bookmark.circle'
  | 'bookmark.circle.fill'
  | 'flag'
  | 'flag.fill'
  | 'flag.circle'
  | 'flag.circle.fill'
  | 'globe'
  | 'globe.europe.africa'
  | 'globe.americas'
  | 'globe.asia.australia'
  | 'map'
  | 'map.fill'
  | 'map.circle'
  | 'map.circle.fill'
  | 'phone'
  | 'phone.fill'
  | 'phone.circle'
  | 'phone.circle.fill'
  | 'message'
  | 'message.fill'
  | 'message.circle'
  | 'message.circle.fill'
  | 'mail'
  | 'mail.fill'
  | 'mail.circle'
  | 'mail.circle.fill'
  | 'cart'
  | 'cart.fill'
  | 'cart.circle'
  | 'cart.circle.fill'
  | 'creditcard'
  | 'creditcard.fill'
  | 'creditcard.circle'
  | 'creditcard.circle.fill'
  | 'gift'
  | 'gift.fill'
  | 'gift.circle'
  | 'gift.circle.fill'
  | 'location'
  | 'location.fill'
  | 'location.circle'
  | 'location.circle.fill'
  | 'link'
  | 'link.circle'
  | 'link.circle.fill'
  | 'cloud'
  | 'cloud.fill'
  | 'cloud.circle'
  | 'cloud.circle.fill'
  | 'download'
  | 'download.circle'
  | 'download.circle.fill'
  | 'upload'
  | 'upload.circle'
  | 'upload.circle.fill'
  | 'play'
  | 'play.fill'
  | 'play.circle'
  | 'play.circle.fill'
  | 'pause'
  | 'pause.fill'
  | 'pause.circle'
  | 'pause.circle.fill'
  | 'stop'
  | 'stop.fill'
  | 'stop.circle'
  | 'stop.circle.fill'
  | 'refresh'
  | 'refresh.circle'
  | 'refresh.circle.fill'
  | 'share'
  | 'share.circle'
  | 'share.circle.fill'
  | 'filter'
  | 'filter.circle'
  | 'filter.circle.fill'
  | 'slider.horizontal.3'
  | 'slider.vertical.3';

const MAPPING: Record<IconSymbolName, ComponentProps<typeof MaterialIcons>['name']> = {
  'house.fill': 'home',
  'paperplane.fill': 'send',
  'chevron.left.forwardslash.chevron.right': 'code',
  'chevron.right': 'chevron-right',
  'chevron.left': 'chevron-left',
  'chevron.up': 'expand-less',
  'chevron.down': 'expand-more',
  'ellipsis': 'more-vert',
  'ellipsis.circle': 'more-horiz',
  'ellipsis.circle.fill': 'more-horiz',
  'gear': 'settings',
  'gear.fill': 'settings',
  'bell': 'notifications',
  'bell.fill': 'notifications',
  'bell.slash': 'notifications-off',
  'bell.slash.fill': 'notifications-off',
  'magnifyingglass': 'search',
  'magnifyingglass.circle': 'search',
  'magnifyingglass.circle.fill': 'search',
  'plus': 'add',
  'plus.circle': 'add-circle',
  'plus.circle.fill': 'add-circle',
  'minus': 'remove',
  'minus.circle': 'remove-circle',
  'minus.circle.fill': 'remove-circle',
  'arrow.up': 'arrow-upward',
  'arrow.down': 'arrow-downward',
  'arrow.left': 'arrow-back',
  'arrow.right': 'arrow-forward',
  'arrow.up.circle': 'arrow-upward',
  'arrow.down.circle': 'arrow-downward',
  'arrow.left.circle': 'arrow-back',
  'arrow.right.circle': 'arrow-forward',
  'arrow.up.circle.fill': 'arrow-upward',
  'arrow.down.circle.fill': 'arrow-downward',
  'arrow.left.circle.fill': 'arrow-back',
  'arrow.right.circle.fill': 'arrow-forward',
  'star': 'star-outline',
  'star.fill': 'star',
  'star.circle': 'star-outline',
  'star.circle.fill': 'star',
  'heart': 'favorite-border',
  'heart.fill': 'favorite',
  'heart.circle': 'favorite-border',
  'heart.circle.fill': 'favorite',
  'trash': 'delete-outline',
  'trash.fill': 'delete',
  'trash.circle': 'delete-outline',
  'trash.circle.fill': 'delete',
  'pencil': 'edit',
  'pencil.circle': 'edit',
  'pencil.circle.fill': 'edit',
  'checkmark': 'check',
  'checkmark.circle': 'check-circle-outline',
  'checkmark.circle.fill': 'check-circle',
  'xmark': 'close',
  'xmark.circle': 'cancel',
  'xmark.circle.fill': 'cancel',
  'eye': 'visibility',
  'eye.fill': 'visibility',
  'eye.slash': 'visibility-off',
  'eye.slash.fill': 'visibility-off',
  'person': 'person-outline',
  'person.fill': 'person',
  'person.circle': 'person-outline',
  'person.circle.fill': 'person',
  'calendar': 'calendar-today',
  'calendar.circle': 'calendar-today',
  'calendar.circle.fill': 'calendar-today',
  'clock': 'access-time',
  'clock.fill': 'access-time',
  'clock.circle': 'access-time',
  'clock.circle.fill': 'access-time',
  'camera': 'photo-camera',
  'camera.fill': 'photo-camera',
  'camera.circle': 'photo-camera',
  'camera.circle.fill': 'photo-camera',
  'photo': 'image',
  'photo.fill': 'image',
  'photo.circle': 'image',
  'photo.circle.fill': 'image',
  'folder': 'folder-open',
  'folder.fill': 'folder',
  'folder.circle': 'folder-open',
  'folder.circle.fill': 'folder',
  'doc': 'insert-drive-file',
  'doc.fill': 'description',
  'doc.circle': 'insert-drive-file',
  'doc.circle.fill': 'description',
  'lock': 'lock-outline',
  'lock.fill': 'lock',
  'lock.open': 'lock-open',
  'lock.open.fill': 'lock-open',
  'bookmark': 'bookmark-border',
  'bookmark.fill': 'bookmark',
  'bookmark.circle': 'bookmark-border',
  'bookmark.circle.fill': 'bookmark',
  'flag': 'outlined-flag',
  'flag.fill': 'flag',
  'flag.circle': 'outlined-flag',
  'flag.circle.fill': 'flag',
  'globe': 'public',
  'globe.europe.africa': 'public',
  'globe.americas': 'public',
  'globe.asia.australia': 'public',
  'map': 'map',
  'map.fill': 'map',
  'map.circle': 'map',
  'map.circle.fill': 'map',
  'phone': 'phone',
  'phone.fill': 'phone',
  'phone.circle': 'phone',
  'phone.circle.fill': 'phone',
  'message': 'message',
  'message.fill': 'message',
  'message.circle': 'message',
  'message.circle.fill': 'message',
  'mail': 'mail-outline',
  'mail.fill': 'mail',
  'mail.circle': 'mail-outline',
  'mail.circle.fill': 'mail',
  'cart': 'shopping-cart',
  'cart.fill': 'shopping-cart',
  'cart.circle': 'shopping-cart',
  'cart.circle.fill': 'shopping-cart',
  'creditcard': 'credit-card',
  'creditcard.fill': 'credit-card',
  'creditcard.circle': 'credit-card',
  'creditcard.circle.fill': 'credit-card',
  'gift': 'card-giftcard',
  'gift.fill': 'card-giftcard',
  'gift.circle': 'card-giftcard',
  'gift.circle.fill': 'card-giftcard',
  'location': 'location-on',
  'location.fill': 'location-on',
  'location.circle': 'location-on',
  'location.circle.fill': 'location-on',
  'link': 'link',
  'link.circle': 'link',
  'link.circle.fill': 'link',
  'cloud': 'cloud-queue',
  'cloud.fill': 'cloud',
  'cloud.circle': 'cloud-queue',
  'cloud.circle.fill': 'cloud',
  'download': 'file-download',
  'download.circle': 'file-download',
  'download.circle.fill': 'file-download',
  'upload': 'file-upload',
  'upload.circle': 'file-upload',
  'upload.circle.fill': 'file-upload',
  'play': 'play-arrow',
  'play.fill': 'play-arrow',
  'play.circle': 'play-circle-outline',
  'play.circle.fill': 'play-circle',
  'pause': 'pause',
  'pause.fill': 'pause',
  'pause.circle': 'pause-circle-outline',
  'pause.circle.fill': 'pause-circle',
  'stop': 'stop',
  'stop.fill': 'stop',
  'stop.circle': 'stop-circle',
  'stop.circle.fill': 'stop-circle',
  'refresh': 'refresh',
  'refresh.circle': 'refresh',
  'refresh.circle.fill': 'refresh',
  'share': 'share',
  'share.circle': 'share',
  'share.circle.fill': 'share',
  'filter': 'filter-list',
  'filter.circle': 'filter-list',
  'filter.circle.fill': 'filter-list',
  'slider.horizontal.3': 'tune',
  'slider.vertical.3': 'tune',
  
};

/**
 * An icon component that uses native SF Symbols on iOS, and Material Icons on Android and web.
 * This ensures a consistent look across platforms, and optimal resource usage.
 * Icon `name`s are based on SF Symbols and require manual mapping to Material Icons.
 */
export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}
